apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: all-service-sm
  namespace: observability
  labels:
    release: prometheus  
spec:
  selector:
    matchLabels:
      monitor: prometheus
  namespaceSelector:
    matchNames:
    - applications
  endpoints:
  - port: http
    path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mysql-sm
  namespace: observability
  labels:
    release: prometheus  
spec:
  selector:
    matchLabels:
      app: mysql
  namespaceSelector:
    matchNames:
    - applications
  endpoints:
  - port: http
    path: /metrics